/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GSlugRouteImport } from './routes/g.$slug'
import { Route as ROwnerIdIdRouteImport } from './routes/r.$ownerId.$id'
import { Route as GSlugVideoRouteImport } from './routes/g.$slug.video'
import { Route as GSlugRRecipeIdRouteImport } from './routes/g.$slug_.r.$recipeId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GSlugRoute = GSlugRouteImport.update({
  id: '/g/$slug',
  path: '/g/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ROwnerIdIdRoute = ROwnerIdIdRouteImport.update({
  id: '/r/$ownerId/$id',
  path: '/r/$ownerId/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GSlugVideoRoute = GSlugVideoRouteImport.update({
  id: '/video',
  path: '/video',
  getParentRoute: () => GSlugRoute,
} as any)
const GSlugRRecipeIdRoute = GSlugRRecipeIdRouteImport.update({
  id: '/g/$slug_/r/$recipeId',
  path: '/g/$slug/r/$recipeId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/app': typeof AppRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/g/$slug': typeof GSlugRouteWithChildren
  '/g/$slug/video': typeof GSlugVideoRoute
  '/r/$ownerId/$id': typeof ROwnerIdIdRoute
  '/g/$slug/r/$recipeId': typeof GSlugRRecipeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/app': typeof AppRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/g/$slug': typeof GSlugRouteWithChildren
  '/g/$slug/video': typeof GSlugVideoRoute
  '/r/$ownerId/$id': typeof ROwnerIdIdRoute
  '/g/$slug/r/$recipeId': typeof GSlugRRecipeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/app': typeof AppRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/register': typeof RegisterRoute
  '/g/$slug': typeof GSlugRouteWithChildren
  '/g/$slug/video': typeof GSlugVideoRoute
  '/r/$ownerId/$id': typeof ROwnerIdIdRoute
  '/g/$slug_/r/$recipeId': typeof GSlugRRecipeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/pricing'
    | '/register'
    | '/g/$slug'
    | '/g/$slug/video'
    | '/r/$ownerId/$id'
    | '/g/$slug/r/$recipeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/pricing'
    | '/register'
    | '/g/$slug'
    | '/g/$slug/video'
    | '/r/$ownerId/$id'
    | '/g/$slug/r/$recipeId'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/app'
    | '/login'
    | '/onboarding'
    | '/pricing'
    | '/register'
    | '/g/$slug'
    | '/g/$slug/video'
    | '/r/$ownerId/$id'
    | '/g/$slug_/r/$recipeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AppRoute: typeof AppRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PricingRoute: typeof PricingRoute
  RegisterRoute: typeof RegisterRoute
  GSlugRoute: typeof GSlugRouteWithChildren
  ROwnerIdIdRoute: typeof ROwnerIdIdRoute
  GSlugRRecipeIdRoute: typeof GSlugRRecipeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/g/$slug': {
      id: '/g/$slug'
      path: '/g/$slug'
      fullPath: '/g/$slug'
      preLoaderRoute: typeof GSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$ownerId/$id': {
      id: '/r/$ownerId/$id'
      path: '/r/$ownerId/$id'
      fullPath: '/r/$ownerId/$id'
      preLoaderRoute: typeof ROwnerIdIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/g/$slug/video': {
      id: '/g/$slug/video'
      path: '/video'
      fullPath: '/g/$slug/video'
      preLoaderRoute: typeof GSlugVideoRouteImport
      parentRoute: typeof GSlugRoute
    }
    '/g/$slug_/r/$recipeId': {
      id: '/g/$slug_/r/$recipeId'
      path: '/g/$slug/r/$recipeId'
      fullPath: '/g/$slug/r/$recipeId'
      preLoaderRoute: typeof GSlugRRecipeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface GSlugRouteChildren {
  GSlugVideoRoute: typeof GSlugVideoRoute
}

const GSlugRouteChildren: GSlugRouteChildren = {
  GSlugVideoRoute: GSlugVideoRoute,
}

const GSlugRouteWithChildren = GSlugRoute._addFileChildren(GSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AppRoute: AppRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PricingRoute: PricingRoute,
  RegisterRoute: RegisterRoute,
  GSlugRoute: GSlugRouteWithChildren,
  ROwnerIdIdRoute: ROwnerIdIdRoute,
  GSlugRRecipeIdRoute: GSlugRRecipeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
